server:
  servlet:
    context-path: /api/v1
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/db_oouthapp
    username: root
    password: Adedorcas64#

jwt:
  expiration:
    time: 1800000